/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as FieldRouteImport } from './routes/field'
import { Route as KeepawayRouteImport } from './routes/keepaway'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LocatorRouteImport } from './routes/locator'
import { Route as MissingRouteImport } from './routes/missing'
import { Route as StrobeRouteImport } from './routes/strobe'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as ValleeRouteImport } from './routes/vallee'
import { Route as SitesIdRouteImport } from './routes/sites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepawayRoute = KeepawayRouteImport.update({
  id: '/keepaway',
  path: '/keepaway',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LocatorRoute = LocatorRouteImport.update({
  id: '/locator',
  path: '/locator',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingRoute = MissingRouteImport.update({
  id: '/missing',
  path: '/missing',
  getParentRoute: () => rootRouteImport,
} as any)
const StrobeRoute = StrobeRouteImport.update({
  id: '/strobe',
  path: '/strobe',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const ValleeRoute = ValleeRouteImport.update({
  id: '/vallee',
  path: '/vallee',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/field': typeof FieldRoute
  '/keepaway': typeof KeepawayRoute
  '/library': typeof LibraryRoute
  '/locator': typeof LocatorRoute
  '/missing': typeof MissingRoute
  '/strobe': typeof StrobeRoute
  '/theory': typeof TheoryRoute
  '/vallee': typeof ValleeRoute
  '/sites/$id': typeof SitesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/field': typeof FieldRoute
  '/keepaway': typeof KeepawayRoute
  '/library': typeof LibraryRoute
  '/locator': typeof LocatorRoute
  '/missing': typeof MissingRoute
  '/strobe': typeof StrobeRoute
  '/theory': typeof TheoryRoute
  '/vallee': typeof ValleeRoute
  '/sites/$id': typeof SitesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/field': typeof FieldRoute
  '/keepaway': typeof KeepawayRoute
  '/library': typeof LibraryRoute
  '/locator': typeof LocatorRoute
  '/missing': typeof MissingRoute
  '/strobe': typeof StrobeRoute
  '/theory': typeof TheoryRoute
  '/vallee': typeof ValleeRoute
  '/sites/$id': typeof SitesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/field'
    | '/keepaway'
    | '/library'
    | '/locator'
    | '/missing'
    | '/strobe'
    | '/theory'
    | '/vallee'
    | '/sites/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/field'
    | '/keepaway'
    | '/library'
    | '/locator'
    | '/missing'
    | '/strobe'
    | '/theory'
    | '/vallee'
    | '/sites/$id'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/field'
    | '/keepaway'
    | '/library'
    | '/locator'
    | '/missing'
    | '/strobe'
    | '/theory'
    | '/vallee'
    | '/sites/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  FieldRoute: typeof FieldRoute
  KeepawayRoute: typeof KeepawayRoute
  LibraryRoute: typeof LibraryRoute
  LocatorRoute: typeof LocatorRoute
  MissingRoute: typeof MissingRoute
  StrobeRoute: typeof StrobeRoute
  TheoryRoute: typeof TheoryRoute
  ValleeRoute: typeof ValleeRoute
  SitesIdRoute: typeof SitesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keepaway': {
      id: '/keepaway'
      path: '/keepaway'
      fullPath: '/keepaway'
      preLoaderRoute: typeof KeepawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locator': {
      id: '/locator'
      path: '/locator'
      fullPath: '/locator'
      preLoaderRoute: typeof LocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing': {
      id: '/missing'
      path: '/missing'
      fullPath: '/missing'
      preLoaderRoute: typeof MissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strobe': {
      id: '/strobe'
      path: '/strobe'
      fullPath: '/strobe'
      preLoaderRoute: typeof StrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vallee': {
      id: '/vallee'
      path: '/vallee'
      fullPath: '/vallee'
      preLoaderRoute: typeof ValleeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  FieldRoute: FieldRoute,
  KeepawayRoute: KeepawayRoute,
  LibraryRoute: LibraryRoute,
  LocatorRoute: LocatorRoute,
  MissingRoute: MissingRoute,
  StrobeRoute: StrobeRoute,
  TheoryRoute: TheoryRoute,
  ValleeRoute: ValleeRoute,
  SitesIdRoute: SitesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
